CREATE TABLE IF NOT EXISTS cocktail (
    cocktail_name TEXT PRIMARY KEY,
    alcoholic BOOLEAN NOT NULL,
    image_url TEXT,
    glass_type TEXT,
    recipe TEXT,
    ingredients TEXT[],
    ingredient1 TEXT,
    ingredient2 TEXT,
    ingredient3 TEXT,
    ingredient4 TEXT,
    ingredient5 TEXT,
    ingredient6 TEXT,
    ingredient7 TEXT,
    ingredient8 TEXT,
    ingredient9 TEXT,
    ingredient10 TEXT,
    ingredient11 TEXT,
    ingredient12 TEXT,
    ingredient13 TEXT,
    ingredient14 TEXT,
    ingredient15 TEXT,
    measure1 TEXT,
    measure2 TEXT,
    measure3 TEXT,
    measure4 TEXT,
    measure5 TEXT,
    measure6 TEXT,
    measure7 TEXT,
    measure8 TEXT,
    measure9 TEXT,
    measure10 TEXT,
    measure11 TEXT,
    measure12 TEXT,
    measure13 TEXT,
    measure14 TEXT,
    measure15 TEXT
);
